color:
  saturation: 0.01971326
  brandStrength: 0.7791701
  rhythmicContrast: 0.02688172
  brandColors:
    - '#C89B76'
    - '#FFFFFF'
    - '#412830'
    - '#885338'
    - '#020101'
  lightness: 0.3189964
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0
typography_spectrum: 0.9032258
name: Masiv
